# Generated by Django 2.2.6 on 2019-11-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20191106_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
