# Generated by Django 2.2.6 on 2019-11-07 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20191106_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile'),
        ),
    ]
