# Generated by Django 2.2.6 on 2019-11-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20191106_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Profile.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('id', 'title', 'body')},
        ),
    ]
