# Generated by Django 2.2.6 on 2019-11-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_post_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
    ]
