# Generated by Django 2.2.6 on 2019-11-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_auto_20191113_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Owner',
            new_name='owner',
        ),
    ]
