# Generated by Django 2.2.6 on 2019-11-13 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0009_auto_20191108_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_complement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_complement', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
