# Generated by Django 2.2.6 on 2019-11-13 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_profile_user_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_complement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complement', to=settings.AUTH_USER_MODEL),
        ),
    ]
