# Generated by Django 2.2.6 on 2019-11-13 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_auto_20191113_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_complement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_complement', to=settings.AUTH_USER_MODEL),
        ),
    ]
