# Generated by Django 2.2.6 on 2019-11-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=350),
        ),
    ]
